### ISSUE TITLE
version 2 sketch

### ISSUE THREAD

**Issue by dosumis** [celltag/celltag_schema#7]
Status: DRAFT; INCOMPLETE

Aims:

1. Strictly and explictly limit schema to cell type/class/state annotation rather than generic, extensible metaschema.  This allows for more straightforward flattening.
2. Work backwards from flattened representation(s) in order to choose clear field names that work for flattening as well as when seen in isolation.
3. Support flattened representation as dot paths in obs key names.
4. Aim for cleaner user-facing documentation - Evan's schema of required doc is a good starting point.

Flattened representation for AnnData obs:

cell_type.marker_evidence; cell_type.location; cell_type.location.evidence; cell_type.location.evidence.comment;

Schema sketch:

```yaml

cell_type_annotation_metadata:  # formerly meta ->   # maybe remove type?

   annotation_type: # formerly field_type
      description: This field records type of annotation on a cell.
      Rationale: we need to distinguish ontology vs author cell type & author cell state
      values: (ENUM)
         -  cell_type_ontology_label
        -  cell_type_ontology_id
        -  author_cell_type_name # Could potentially distinguish abbreviations from full names here. 
        -  author_cell_state_name
      flattening_notes: 
 
# field_relationship-> remove this in favor of fields named for relationship

   narrower_than:
      value: name of another cell type field
      notes:  >
      When recording at the single-cell level, it is sufficient to record a field name,
    but outside of that context we need a way to refer to cell sets.  
    If sets are defined by labels, then maybe the value should be key:label?  

   exact_match: 
       value: name of another cell type field

   evidence:
      markers: 
         description:  use this to record marker expression used as evidence for cell type assignment
          value: list of marker objects
          notes on flattening: names only
      negative_markers: 
          description:  use this to record genes whose lack of expression or low expression was used as evidence for cell_type assignment
          value: list of marker objects
      comment: 
         description: use this to record a free text description of the evidence for cell type assignment
         value: string 
 annotation_transfer: 
       algorithm
            name:
            version: 
            doi:  (optional)
       reference_data:
       reference_cluster: 

Marker object: 
    name:
    id: (optional)

```
